"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-10-04 23:27:24.918450
"""
from alembic import op
import sqlalchemy as sa


revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('business_name', sa.String(length=160), nullable=True),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone')
    )
    op.create_table('people',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('normalized_name', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'normalized_name', name='uq_people_user_name')
    )
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_people_user_id'), ['user_id'], unique=False)

    op.create_table('reports',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('period_start', sa.Date(), nullable=True),
    sa.Column('period_end', sa.Date(), nullable=True),
    sa.Column('snapshot', sa.JSON(), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.Column('share_token', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'REVOKED', name='reportstatus', native_enum=False, length=20), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('share_token')
    )
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reports_user_id'), ['user_id'], unique=False)

    op.create_table('uploads',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.Enum('PHOTO', 'VOICE', 'TEXT', name='uploadtype', native_enum=False, length=20), nullable=False),
    sa.Column('file_url', sa.String(length=512), nullable=True),
    sa.Column('original_filename', sa.String(length=255), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('status', sa.Enum('UPLOADED', 'PROCESSING', 'REVIEW', 'CONFIRMED', 'FAILED', name='uploadstatus', native_enum=False, length=20), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('error_message', sa.String(length=500), nullable=True),
    sa.Column('pipeline_info', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('uploads', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_uploads_sha256'), ['sha256'], unique=False)
        batch_op.create_index(batch_op.f('ix_uploads_user_id'), ['user_id'], unique=False)

    op.create_table('source_pages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('upload_id', sa.String(length=36), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(length=512), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('lines', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['upload_id'], ['uploads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('source_pages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_source_pages_upload_id'), ['upload_id'], unique=False)

    op.create_table('records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('upload_id', sa.String(length=36), nullable=False),
    sa.Column('source_page_id', sa.String(length=36), nullable=True),
    sa.Column('person_id', sa.String(length=36), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('type', sa.Enum('SALE', 'DEBT', 'EXPENSE', 'RESTOCK', 'PAYMENT', 'OTHER', name='recordtype', native_enum=False, length=20), nullable=True),
    sa.Column('item', sa.String(length=160), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('person', sa.String(length=120), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('field_confidence', sa.JSON(), nullable=True),
    sa.Column('validation_issues', sa.JSON(), nullable=True),
    sa.Column('ai_original', sa.JSON(), nullable=True),
    sa.Column('edited', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('AI_EXTRACTED', 'NEEDS_REVIEW', 'CONFIRMED', 'REJECTED', name='recordstatus', native_enum=False, length=20), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('source_reference', sa.String(length=64), nullable=True),
    sa.Column('line_index', sa.Integer(), nullable=True),
    sa.Column('original_text', sa.String(length=500), nullable=True),
    sa.Column('bbox_x', sa.Float(), nullable=True),
    sa.Column('bbox_y', sa.Float(), nullable=True),
    sa.Column('bbox_width', sa.Float(), nullable=True),
    sa.Column('bbox_height', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_page_id'], ['source_pages.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['upload_id'], ['uploads.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_records_upload_id'), ['upload_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_records_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_records_user_id'))
        batch_op.drop_index(batch_op.f('ix_records_upload_id'))

    op.drop_table('records')
    with op.batch_alter_table('source_pages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_source_pages_upload_id'))

    op.drop_table('source_pages')
    with op.batch_alter_table('uploads', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_uploads_user_id'))
        batch_op.drop_index(batch_op.f('ix_uploads_sha256'))

    op.drop_table('uploads')
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reports_user_id'))

    op.drop_table('reports')
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_people_user_id'))

    op.drop_table('people')
    op.drop_table('users')
    # ### end Alembic commands ###
